-- init/init.sql
CREATE DATABASE ecws;
CREATE USER ecws WITH ENCRYPTED PASSWORD 'ecws';
GRANT ALL PRIVILEGES ON DATABASE ecws TO ecws;

\c ecws;


-- Grant ownership of schema to ecws user
CREATE SCHEMA ecws AUTHORIZATION ecws;

-- Switch to ecws user for subsequent operations
SET ROLE ecws;

-- Switch to the ecws database

-- ecws.cart definition

-- Drop table

-- DROP TABLE ecws.cart;

CREATE TABLE ecws.cart (
	cart_id bigserial NOT NULL,
	created_at timestamp NULL,
	status varchar(255) NULL,
	total_price float8 NULL,
	updated_at timestamp NULL,
	CONSTRAINT cart_pkey PRIMARY KEY (cart_id)
);


-- ecws.order definition

-- Drop table

-- DROP TABLE ecws.order;

CREATE TABLE ecws.order (
	order_id bigserial NOT NULL,
	billing_address varchar(255) NULL,
	customer_id int8 NULL,
	order_date date NULL,
	order_status varchar(255) NULL,
	payment_method varchar(255) NULL,
	shipping_address varchar(255) NULL,
	total_amount float8 NULL,
	CONSTRAINT order_pkey PRIMARY KEY (order_id)
);


-- ecws.product definition

-- Drop table

-- DROP TABLE ecws.product;

CREATE TABLE ecws.product (
	product_id bigserial NOT NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	price float8 NOT NULL,
	category varchar(255) NULL,
	created_at timestamp(6) NULL,
	image_url varchar(255) NULL,
	stock_quantity int4 NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT product_pkey PRIMARY KEY (product_id)
);


-- ecws.cart_items definition

-- Drop table

-- DROP TABLE ecws.cart_items;

CREATE TABLE ecws.cart_item (
	cart_item_id bigserial NOT NULL,
	product_id int8 NULL,
	quantity int4 NULL,
	cart_id int8 NULL,
	CONSTRAINT cart_items_pkey PRIMARY KEY (cart_item_id),
	CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES ecws.cart(cart_id)
);


-- ecws.order_item definition

-- Drop table

-- DROP TABLE ecws.order_item;

CREATE TABLE ecws.order_item (
	order_item_id bigserial NOT NULL,
	price float8 NULL,
	product_id int8 NULL,
	quantity int4 NULL,
	order_id int8 NULL,
	CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id),
	CONSTRAINT fkt4dc2r9nbvbujrljv3e23iibt FOREIGN KEY (order_id) REFERENCES ecws.order(order_id)
);

-- ecws.user_data definition

-- Drop table

-- DROP TABLE ecws.user_data;

CREATE TABLE ecws.user_data (
	user_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	"password" varchar(255) NULL,
	"role" int4 NULL,
	username varchar(255) NULL,
	CONSTRAINT user_data_pkey PRIMARY KEY (user_id)
);